apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-kooijman-tls
  namespace: gitlab
spec:
  # Secret names are always required.
  secretName: gitlab-kooijman-tls
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  commonName: gitlab.kooijman.se
  dnsNames:
    - reg.gitlab.kooijman.se
    - gitlab.kooijman.se
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer